### ISSUE TITLE
HacktoberFest20

### ISSUE THREAD

**Issue by kiransbaliga** [TechOUs/Algorithms#102]
## Name the program which you are adding

Binary search using recursion, Queue using linked list, Implementation of Sparse matrix and its addition

## Programming Language you will code

C++ for Binary Search and C for Queue and Sparse Matrix

## YOU ARE

a student

## GITHUB USERNAME

kiransbaliga  [https://github.com/kiransbaliga]

**Comment by Swatichanchal** [comment]
- Print KPC . (key to character map )
- Python for string problem
- I'm a student
-  Swatichanchal [https://github.com/Swatichanchal]

**Comment by GauravWalia19** [comment]
@Swatichanchal can you please create a new issue with the HacktoberFest20 template.

**Comment by GauravWalia19** [comment]
@kiransbaliga 

**Binary search using recursion in C++** is already present we will not accept this
**Queue using linked list** create a issue on our Data-Structure repository for this.
 **Implementation of Sparse matrix and its addition** for this please send a PR

**Comment by kiransbaliga** [comment]
okay thanks

**Comment by Swatichanchal** [comment]
> @Swatichanchal can you please create a new issue with the HacktoberFest20 template.

Yeah sure
