### ISSUE TITLE
Key to character mapping using any language

### ISSUE THREAD

**Issue by Swatichanchal** [TechOUs/Algorithms#113]
print possible sequence of characters based on entered key (number ) . 
key to character mapping is based on mobile phone key pad sequence .
You can submit your code in any language .

**Comment by bhaveshjakhar** [comment]
Project - Patterns using python 
 User name- bhaveshjakhar
 Status - Student

**Comment by zarasingh199** [comment]
Project - Rhombus Pyramid by Python
User name- zarasingh199
Status - Student

**Comment by GauravWalia19** [comment]
@bhaveshjakhar @zarasingh199 please create a new issue for your algorithm which you want to add. Make sure you use HacktoberFest20 template.

**Comment by bhaveshjakhar** [comment]
> 
> 
> @bhaveshjakhar @zarasingh199 please create a new issue for your algorithm which you want to add. Make sure you use HacktoberFest20 template.

okay
