### ISSUE TITLE
Pattern Using Python

### ISSUE THREAD

**Issue by zarasingh199** [TechOUs/Algorithms#118]
Rhombus pattern using python logic.

**Comment by zarasingh199** [comment]
Pattern using Python

**Comment by GauravWalia19** [comment]
This seems like a diamond pattern not rhombus pattern. Please be specific.

**Comment by zarasingh199** [comment]
> This seems like a diamond pattern not rhombus pattern. Please be specific.

In code it is rhombus, mention not, I'll correct it.
