### ISSUE TITLE
subsequence of a string 

### ISSUE THREAD

**Issue by PreekshitChandel** [TechOUs/Algorithms#119]
print a subsequence of string

**Comment by sammanchanchal** [comment]
Project - dynamic programming problems 
student
sammanchanchal

**Comment by shrutisingh11** [comment]
I also want to contribute in dynamic programming problems 
please assign me this task
Project - coin change permutation 
language - python
student
shrutisingh11

**Comment by GauravWalia19** [comment]
@sammanchanchal @shrutisingh11 there is the HacktoberFest20 issue template in this repository please use that and create a issue. We will discuss there whether we can accept your given algorithm or not.
