### ISSUE TITLE
Error cloning caused by naming.

### ISSUE THREAD

**Issue by JaniniRami07** [TechOUs/Algorithms#147]
**Describe the bug**
While I was trying to clone this repository I had this error:
```
Cloning into 'Algorithms'...
remote: Enumerating objects: 88, done.
remote: Counting objects: 100% (88/88), done.
remote: Compressing objects: 100% (70/70), done.
remote: Total 819 (delta 21), reused 61 (delta 8), pack-reused 731Receiving objects:  93% (762/819)
Receiving objects: 100% (819/819), 219.36 KiB | 1.02 MiB/s, done.
Resolving deltas: 100% (304/304), done.
error: invalid path 'MISC/equillibrium_point_in_array./c++.cpp'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```
It is caused by the dot at the end of the folder ```MISC/equillibrium_point_in_array.```, hope you remove it as soon as possible so people and myself could continue contributing to this project!

**To Reproduce**
1. Clone the repository with ```https://github.com/TechOUs/Algorithms``` and the error above will pop up while cloning the repository,

**Expected behavior**
It is expected to be cloned without any problems after the removal of the dot.

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/39865850/96094153-a8ef2580-0ed5-11eb-9080-927f17d27a7f.png)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by GauravWalia19** [comment]
@JaniniRami07 thanks for reporting the issue.
