### ISSUE TITLE
Error in line 3 in program Palindrome.py

### ISSUE THREAD

**Issue by GauravWalia19** [TechOUs/algOrithms#25]
Wrong syntax need to be fixed

**Comment by anarchymonkey** [comment]
@ashwek fixes ?

**Comment by GauravWalia19** [comment]
I will fix it

**Comment by ashwek** [comment]
@anarchymonkey @GauravWalia19 

https://github.com/TechOUs/algOrithms/blob/b9b09c7bdea437e09b71e03b112172ec7e814223/STRINGS/Pallindrome/Python/Pallindrome.py#L3

There is no syntax error.
(this is **Python3** code, if you use **Python 2.x** compiler then it would raise Syntax Error )

**Comment by GauravWalia19** [comment]
yup
